apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot
  name: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-boot
    spec:
      containers:
      - image: hygl/hygl/spring-boot:6
        name: spring-boot
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: spring-boot
  name: spring-boot
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-boot
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: spring-boot-ingress
spec:
  backend:
    serviceName: spring-boot
    servicePort: 8080
